# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
