# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-18 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_routing', '0003_auto_20200118_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=200)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='message_routing.Gateway', unique=True)),
            ],
        ),
    ]
