# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-18 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_routing', '0004_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='gateway',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='message_routing.Gateway'),
        ),
    ]
